openapi: 3.2.0
info:
  contact: {}
  description: APIs for Open Container Initiative Distribution Specification
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Open Container Initiative Distribution Specification Oci API
  version: v1.1.1
tags:
- name: Oci
paths:
  /v2/_oci/ext/discover:
    get:
      description: List all extensions present on registry
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api.ExtensionList'
      summary: List Registry level extensions
      tags:
      - Oci
      operationId: getV2OciExtDiscover
      x-operation-id-source: derived
components:
  schemas:
    extensions.Extension:
      properties:
        description:
          type: string
        endpoints:
          items:
            type: string
          type: array
        name:
          type: string
        url:
          type: string
      type: object
    api.ExtensionList:
      properties:
        extensions:
          items:
            $ref: '#/components/schemas/extensions.Extension'
          type: array
      type: object
