openapi: 3.2.0
info:
  contact: {}
  description: APIs for Open Container Initiative Distribution Specification
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Open Container Initiative Distribution Specification API
  version: v1.1.1
tags:
- name: Open Container Initiative Distribution Specification
paths:
  /v2/:
    get:
      description: Check if this API version is supported
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: string
      summary: Check API support
      tags:
      - Open Container Initiative Distribution Specification
      operationId: getV2
      x-operation-id-source: derived
