swagger: '2.0'
info:
  contact: {}
  description: APIs for Open Container Initiative Distribution Specification
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Blobs Open Container Initiative Distribution Specification API
  version: v1.1.1
tags:
- name: Open Container Initiative Distribution Specification
paths:
  /v2/:
    get:
      consumes:
      - application/json
      description: Check if this API version is supported
      produces:
      - application/json
      responses:
        '200':
          description: ok
          schema:
            type: string
      summary: Check API support
      tags:
      - Open Container Initiative Distribution Specification
