openapi: 3.2.0
info:
  contact: {}
  description: APIs for Open Container Initiative Distribution Specification
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Open Container Initiative Distribution Specification Tags…
  version: v1.1.1
tags:
- name: Tags
paths:
  /v2/{name}/tags/list:
    get:
      description: List all image tags in a repository
      parameters:
      - description: repository name
        in: path
        name: name
        required: true
        schema:
          type: string
      - description: limit entries for pagination
        in: query
        name: n
        required: true
        schema:
          type: integer
      - description: last tag value for pagination
        in: query
        name: last
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/common.ImageTags'
        '400':
          description: bad request
          content:
            application/json:
              schema:
                type: string
        '404':
          description: not found
          content:
            application/json:
              schema:
                type: string
      summary: List image tags
      tags:
      - Tags
      operationId: getV2ByNameTagsList
      x-operation-id-source: derived
components:
  schemas:
    common.ImageTags:
      properties:
        name:
          type: string
        tags:
          items:
            type: string
          type: array
      type: object
