openapi: 3.2.0
info:
  contact: {}
  description: APIs for Open Container Initiative Distribution Specification
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Open Container Initiative Distribution Specification…
  version: v1.1.1
tags:
- name: Catalog
paths:
  /v2/_catalog:
    get:
      description: List all image repositories
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api.RepositoryList'
        '500':
          description: internal server error
          content:
            application/json:
              schema:
                type: string
      summary: List image repositories
      tags:
      - Catalog
      operationId: getV2Catalog
      x-operation-id-source: derived
components:
  schemas:
    api.RepositoryList:
      properties:
        repositories:
          items:
            type: string
          type: array
      type: object
